name: Deploy Lambda with Terraform

on:
  workflow_dispatch: # Trigger manuale

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    # Set up Terraform CLI
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    # Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # Plan Terraform changes
    - name: Terraform Plan
      run: terraform plan -out=tfplan

    # Apply Terraform changes
    - name: Terraform Apply
      if: github.event.inputs.auto_apply == 'true' # Opzionale: controllo per applicazione automatica
      run: terraform apply -auto-approve tfplan